### ISSUE TITLE
Invalid pointer bug

### ISSUE THREAD

**Issue by kshepitzki** [akupila/Arduino-MMA8452#1]
The function 'read' in MMA8452.cpp:
uint8_t MMA8452::read(uint8_t reg) {
	uint8_t *buf = 0;
	readMultiple(reg, buf, 1);
	return *buf;
}
defines an uninitialized pointer to uint8_t (the pointer does not point to a valid location in memory). This causes undefined behavior.
The function should be:
uint8_t MMA8452::read(uint8_t reg) {
	uint8_t buf = 0;
	readMultiple(reg, &buf, 1);
	return buf;
}

**Comment by akupila** [comment]
Fixed with https://github.com/akupila/Arduino-MMA8452/pull/2 - thanks @kshepitzki!
